//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanHang.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Comment
    {
        public int Id { get; set; }
        public Nullable<int> IdUser { get; set; }
        public string UserComment { get; set; }
        public string AdminRequest { get; set; }
        public Nullable<System.DateTime> Day { get; set; }
        [Display(Name = "Ngày trả lời")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> Dayresquest { get; set; }
    }
}
